apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: peproxy
  namespace: default
  labels:
    team: teampeon
  image: docker.pkg.github.com/navikt/peproxy/peproxy:2020.03.31-409d3f8
  port: 8080
  ingresses:
    - https://peproxy.nais.preprod.local
  liveness:
    path: internal/isAlive
    initialDelay: 30
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: internal/isReady
    initialDelay: 30
    periodSeconds: 1
    failureThreshold: 60
  replicas:
    min: 1
    max: 2
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "nav"
